//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartSellerWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Case
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Case()
        {
            this.Part = new HashSet<Part>();
            this.SupportedFormFactorSupply = new HashSet<SupportedFormFactorSupply>();
        }
    
        public int ID { get; set; }
        public int BrandID { get; set; }
        public string Model { get; set; }
        public int Width { get; set; }
        public int Height { get; set; }
        public int Length { get; set; }
        public int SupplyLength { get; set; }
        public int GPULength { get; set; }
        public int CoolerLength { get; set; }
        public int FormFactorID { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual FormFactor FormFactor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Part> Part { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupportedFormFactorSupply> SupportedFormFactorSupply { get; set; }
    }
}
