//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartSellerWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CPU()
        {
            this.Part = new HashSet<Part>();
        }
    
        public int ID { get; set; }
        public int BrandID { get; set; }
        public string Model { get; set; }
        public int Voltage { get; set; }
        public int SocketID { get; set; }
        public int Cores { get; set; }
        public int Threads { get; set; }
        public decimal Frequency { get; set; }
        public int L1 { get; set; }
        public int L2 { get; set; }
        public int HasTurboBoost { get; set; }
        public Nullable<decimal> MaxFrequency { get; set; }
    
        public virtual Brand Brand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Part> Part { get; set; }
        public virtual Socket Socket { get; set; }
    }
}
