//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartSellerWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Motherboard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Motherboard()
        {
            this.Part = new HashSet<Part>();
        }
    
        public int ID { get; set; }
        public int BrandID { get; set; }
        public string Model { get; set; }
        public int SocketID { get; set; }
        public int ChipsetID { get; set; }
        public int RAMTypeID { get; set; }
        public int RAMSlots { get; set; }
        public int MaxRAMCountGB { get; set; }
        public int MaxRAMFrequencyMHz { get; set; }
        public int Width { get; set; }
        public int Height { get; set; }
        public int SATASlots { get; set; }
        public int M2Slots { get; set; }
        public int NVMe { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual Chipset Chipset { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Part> Part { get; set; }
        public virtual RAMType RAMType { get; set; }
        public virtual Socket Socket { get; set; }
    }
}
