//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartSellerWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Motherboard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Motherboard()
        {
            this.Part = new HashSet<Part>();
        }
    
        public int ID { get; set; }
        public int BrandID { get; set; }
        public string Model { get; set; }
        public string Socket { get; set; }
        public string Chipset { get; set; }
        public string RAMType { get; set; }
        public Nullable<int> RAMSlots { get; set; }
        public Nullable<int> Voltage { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<int> Height { get; set; }
    
        public virtual Brand Brand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Part> Part { get; set; }
    }
}
