//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartSellerWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Part
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Part()
        {
            this.Product = new HashSet<Product>();
        }
    
        public int ID { get; set; }
        public Nullable<int> CPUID { get; set; }
        public Nullable<int> GPUID { get; set; }
        public Nullable<int> SupplyID { get; set; }
        public Nullable<int> RAMID { get; set; }
        public Nullable<int> MotherboardID { get; set; }
        public Nullable<int> DiskID { get; set; }
        public Nullable<int> CoolingID { get; set; }
        public Nullable<int> CaseID { get; set; }
        public string Image { get; set; }
    
        public virtual Case Case { get; set; }
        public virtual Cooling Cooling { get; set; }
        public virtual CPU CPU { get; set; }
        public virtual Disk Disk { get; set; }
        public virtual GPU GPU { get; set; }
        public virtual Motherboard Motherboard { get; set; }
        public virtual RAM RAM { get; set; }
        public virtual Supply Supply { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Product { get; set; }
    }
}
