//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartSellerWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupportedSockets
    {
        public int ID { get; set; }
        public int CoolerID { get; set; }
        public int SocketID { get; set; }
    
        public virtual Cooling Cooling { get; set; }
        public virtual Socket Socket { get; set; }
    }
}
