//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartSellerWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupportedFormFactorSupply
    {
        public int ID { get; set; }
        public int CaseID { get; set; }
        public int FormFactorID { get; set; }
    
        public virtual Case Case { get; set; }
        public virtual FormFactor FormFactor { get; set; }
    }
}
